name: tcache-otp-tokyo-poc

x-otp-common: &otp-common
  image: ${OTP_IMAGE:-docker.io/opentripplanner/opentripplanner:2.10.0@sha256:8d54e5c589186707ee365417f2202dc878c451fa3001b8edff07019531100933}
  environment:
    JAVA_TOOL_OPTIONS: ${OTP_JAVA_OPTIONS:--Xmx6g}
    TZ: Asia/Tokyo
  volumes:
    - ./data/tokyo:/var/opentripplanner
  init: true

services:
  otp:
    <<: *otp-common
    command: ['--load', '--serve']
    ports:
      - '${OTP_PORT:-8080}:8080'
    stop_grace_period: 30s

  otp-build:
    <<: *otp-common
    command: ['--build', '--save']
    profiles: ['build']
